import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Ian's Next Board",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html>
            <body>
                <div id="title-wrap">
                    <a href="/">게시판</a>
                </div>
                {children}
            </body>
        </html>
    );
}
