import type {Metadata} from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
    title: "Ian's Next Board",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html>
        <body>
        <div id="title-wrap">
            <a href="/">게시판</a>
        </div>

        <div id="search-wrap">
            <input type="text" id="search-box" title="검색어를 입력해 주세요."
                   placeholder="제목을 입력하세요."
                   name="board-title"/>
            <button type="button" id="search-btn">검색</button>
        </div>

        {/*<hr/>*/}
        <div id="table-wrap">
            <table>
                <colgroup>
                    <col width="10%"/>
                    <col/>
                    <col width="20%"/>
                </colgroup>
                <thead>
                <tr>
                    <th scope="col">번호</th>
                    <th scope="col">제목</th>
                    <th scope="col">등록일</th>
                </tr>
                </thead>

                <tbody>
                    <tr></tr>
                    <tr>
                        <td>

                            1000
                        </td>
                        <td>
                            asdfasdfa
                        </td>
                        <td>
                            언제고
                        </td>
                    </tr>
                    <tr>
                        <td>
                            1000
                        </td>
                        <td>
                            asdfasdfa
                        </td>
                        <td>
                            언제고
                        </td>
                    </tr>
                    <tr>
                        <td>
                            1000
                        </td>
                        <td>
                            asdfasdfa
                        </td>
                        <td>
                            언제고
                        </td>
                    </tr>
                    <tr>
                        <td>
                            1000
                        </td>
                        <td>
                            asdfasdfa
                        </td>
                        <td>

                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

        <br/>
        </body>
        </html>

        // <html>
        // <body>
        // <h1><a href="/">WEB</a></h1>
        // <ol>
        //     <li><Link href="/read/1">html</Link></li>
        //     <li><Link href="/read/2">css</Link></li>
        // </ol>
        // {children}
        // <ul>
        //     <li><Link href="/create">Create</Link></li>
        //     <li><Link href="/update/1">Update</Link></li>
        //     <li><input type="button" value="delete"/></li>
        // </ul>
        // </body>
        // </html>
    )
}